os: windows
language: node_js
node_js:
- '8'
- '12'
cache:
- directories:
  - "$HOME/.electron"
- npm: true
install: npm install && npm update
before_script: test/ci/_before_script.js
after_success: npm run codecov
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
