step-env: &step-env
  run:
    # prevent Wine popup dialogs about installing additional packages
    name: Setup Environment Variables
    command: |
      echo 'export WINEDLLOVERRIDES="mscoree,mshtml="' >> $BASH_ENV
      echo 'export WINEDEBUG="-all"' >> $BASH_ENV

step-restore-electron-cache: &step-restore-electron-cache
  restore_cache:
    name: Restoring Electron cache
    paths:
      - $HOME/.cache/electron
    keys:
      - v1-electron-cache-{{ arch }}

step-save-electron-cache: &step-save-electron-cache
  save_cache:
    name: Persisting Electron cache
    paths:
      - $HOME/.cache/electron
    key: v1-electron-cache-{{ arch }}

step-before-install: &step-before-install
  run: test/ci/before_install.sh

steps-linux-windows: &steps-linux-windows
  steps:
    - checkout
    - *step-env
    - *step-before-install
    - run: npm install
    - *step-restore-electron-cache
    - run: test/ci/_before_script.js
    - *step-save-electron-cache
    - run: npm test
    - run: npm run codecov

steps-mac: &steps-mac
  steps:
    - checkout
    - *step-env
    - *step-before-install
    - run: npm install --engine-strict
    - *step-restore-electron-cache
    - run: test/ci/_before_script.js
    - *step-save-electron-cache
    - run: npm test
    - run: npm run codecov

version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  test-linux-10:
    docker:
      - image: circleci/node:10
    <<: *steps-linux-windows
  test-linux-12:
    docker:
      - image: circleci/node:12
    <<: *steps-linux-windows
  test-mac:
    macos:
      xcode: "11.3.1"
    <<: *steps-mac
  test-windows:
    executor:
      name: win/vs2019
      shell: bash.exe
    <<: *steps-linux-windows

workflows:
  version: 2
  test:
    jobs:
      - test-linux-10
      - test-linux-12
      - test-mac
      - test-windows
